services:
  base:
    image: open-sesame
    build:
      context: .
      target: development

  server:
    image: open-sesame
    command: npm run dev --workspace=apps/server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/server/node_modules
    ports:
      - "5000:5000"

  "web":
    image: open-sesame
    command: npm run dev --workspace=apps/web -- --host 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
    ports:
      - "3000:3000"
